{% set version = "2.6.1" %}

package:
  name: seccomp-split
  version: {{ version }}

source:
  url: https://github.com/seccomp/libseccomp/releases/download/v{{ version }}/libseccomp-{{ version }}.tar.gz
  sha256: 501f66c667225d53791b97e1d7cf85ab764c297d04881f60f38f451c4b0ee1be
  patches:
    - patches/0001-Dynamic-linking-for-Python-package.patch

build:
  number: 0
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - automake
    - autoconf
    - libtool
    - make
  host:
    - gperf

outputs:
  - name: libseccomp
    script: install_lib.sh
    build:
      run_exports:
        # Has followed semver since 1.0.1 in 2012
        # https://abi-laboratory.pro/index.php?view=timeline&l=libseccomp
        - {{ pin_subpackage('libseccomp') }}
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ stdlib("c") }}
        - make
    test:
      commands:
        - test -f $PREFIX/lib/libseccomp.so
        - test ! -f $PREFIX/lib/libseccomp.a

  - name: seccomp
    script: install_python.sh
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ stdlib("c") }}
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
        - python                                 # [build_platform != target_platform]
        - cython                                 # [build_platform != target_platform]
      host:
        - cython
        - python
        - pip
        - setuptools
        - {{ pin_subpackage('libseccomp', exact=True) }}
      run:
        - {{ pin_subpackage('libseccomp', exact=True) }}
        - python
    test:
      imports:
        - seccomp

about:
  home: https://github.com/seccomp/libseccomp
  license: LGPL-2.1-only
  license_file: LICENSE
  summary: 'libseccomp provides an easy to use, platform independent, interface to the Linux syscall filtering mechanism.'

  description: |
    The libseccomp library provides an easy to use, platform independent, 
    interface to the Linux Kernel's syscall filtering mechanism. The 
    libseccomp API is designed to abstract away the underlying BPF based 
    syscall filter language and present a more conventional function-call
    based filtering interface that should be familiar to, and easily 
    adopted by, application developers.
  dev_url: https://github.com/seccomp/libseccomp

extra:
  recipe-maintainers:
    - mbargull
    - sodre
    - h-vetinari
